# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# Add your own exports, aliases, and functions here.
# Auto-launch zsh shell if in interactive bash
if command -v zsh &> /dev/null; then
  if [[ $(ps --no-header --pid=$PPID --format=comm) != "zsh" && -z ${BASH_EXECUTION_STRING} && ${SHLVL} == 1 ]]
  then
    shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION=''
    exec zsh $LOGIN_OPTION
  fi
fi

# All the default bArchTi aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/barchti/default/bash/rc

#
# Make an alias for invoking commands you use constantly
# alias p='python'

